### PR TITLE
fix(codeartifact-upload): skip existing versions

### PR DESCRIPTION
**Pull request by vixus0**
CI in this repo is currently broken because we try and upload the same version of the `codeartifact-upload-test` package.

### CODE REVIEW

**Review by tajpouria — APPROVED** [review]

**Review by brhutchins — COMMENTED** [review]
Nice. The only issue with having `--skip-existing` by default is that, if you update a package but forget to update the version number, the CI will just silently pass, and then you'll be wondering why you're not seeing your changes in the published package.

Maybe it could be an option in the inputs to the action? 🤔

**Review by tajpouria — APPROVED** [review]

**Comment by brhutchins** [comment]
😞

**Comment by tajpouria** [comment]
@brhutchins Sorry, I didn't noticed the auto merge, but I think `skip-existing` will override the existing version

https://twine.readthedocs.io/en/stable/
```
  --skip-existing       Continue uploading files if one already exists. (Only
                        valid when uploading to PyPI. Other implementations
                        may not support this.)```

**Comment by brhutchins** [comment]
@tajpouria The docs are super vague lol, but looking at the code, I don't think so. It just doesn't raise an exception if it gets the "already exists" error from the repo, but it doesn't upload anything: https://github.com/sigmavirus24/twine/blob/334b92adb85b071cabbb25bcdc68de53800ce35f/twine/commands/upload.py#L121

**Pull request merged**
